spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/res_with_spring_boot_course?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1961
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    # não é mais necessário pois ele pega as configurações padrão do mysql
    # properties:
      # hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false